/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.view;

import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author evand
 */
public class PrincipalJFrame extends javax.swing.JFrame {
    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();

        // Configurando o Ícone do JFrame, carregando uma imagem da pasta resources.
        //String filename = "./src/main/resources/imagens/dollar.png"; // passar filename para ImageIcon também funciona
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("imagens/dollar.png"));
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar2 = new javax.swing.JToolBar();
        jToolBar1 = new javax.swing.JToolBar();
        btnCategorias = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnLancamentos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniCategorias = new javax.swing.JMenuItem();
        mniUsuarios = new javax.swing.JMenuItem();
        mniLancamentos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Contas a Pagar e Receber");
        setExtendedState(6);

        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setRollover(true);

        jToolBar1.setRollover(true);
        jToolBar2.add(jToolBar1);

        btnCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/categories.png"))); // NOI18N
        btnCategorias.setText("Categorias");
        btnCategorias.setFocusable(false);
        btnCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        jToolBar2.add(btnCategorias);

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        btnUsuarios.setText("Usuários");
        btnUsuarios.setFocusable(false);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jToolBar2.add(btnUsuarios);

        btnLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/money.png"))); // NOI18N
        btnLancamentos.setText("Lançamentos");
        btnLancamentos.setFocusable(false);
        btnLancamentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLancamentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancamentosActionPerformed(evt);
            }
        });
        jToolBar2.add(btnLancamentos);

        jMenu1.setText("Operações");

        mniCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/categories16.png"))); // NOI18N
        mniCategorias.setText("Categorias");
        mniCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCategoriasActionPerformed(evt);
            }
        });
        jMenu1.add(mniCategorias);

        mniUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user16.png"))); // NOI18N
        mniUsuarios.setText("Usuários");
        mniUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(mniUsuarios);

        mniLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/money16.png"))); // NOI18N
        mniLancamentos.setText("Lançamentos");
        mniLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLancamentosActionPerformed(evt);
            }
        });
        jMenu1.add(mniLancamentos);
        jMenu1.add(jSeparator1);

        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        jMenu1.add(mniSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        mniSobre.setText("Sobre");
        jMenu2.add(mniSobre);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 218, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(502, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCategoriasActionPerformed
        CategoriaJDialog janela = new CategoriaJDialog(this, true);
        janela.setVisible(true);
    }//GEN-LAST:event_mniCategoriasActionPerformed

    private void mniUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUsuariosActionPerformed
        UsuarioJDialog janela = new UsuarioJDialog(this, true);
        janela.setVisible(true);
    }//GEN-LAST:event_mniUsuariosActionPerformed

    private void mniLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLancamentosActionPerformed
        LancamentosJDialog janela = new LancamentosJDialog(this, true);
        janela.setVisible(true);
    }//GEN-LAST:event_mniLancamentosActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        mniCategoriasActionPerformed(null);
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        mniUsuariosActionPerformed(null);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancamentosActionPerformed
        mniLancamentosActionPerformed(null);
    }//GEN-LAST:event_btnLancamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnLancamentos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem mniCategorias;
    private javax.swing.JMenuItem mniLancamentos;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniSobre;
    private javax.swing.JMenuItem mniUsuarios;
    // End of variables declaration//GEN-END:variables
}
